### PR TITLE
Missing installation of the include directory.

### PR DESCRIPTION
**Pull request by jbedwani**
Adding to the install the content of the include directory. Required when linking code with the dvl_a50 package.

### CODE REVIEW

**Comment by ndahn** [comment]
Sorry, only saw your PR now. I'm not sure, but shouldn't this line already handle this?
https://github.com/ndahn/dvl_a50/blob/1e6a5304235facf53ecf82043fb5ba4c8569016b/CMakeLists.txt#L47C3-L47C31

**Comment by jbedwani** [comment]
Hi,

My understanding is that the INSTALL ( TARGETS ... ) defines the name of a target, then the following DESTINATION tags defines the diverse targeted directory name of the installation.

Using your CMakelist.txt

Clean the install directory for the package: rm -r ./install/dvl_a50
Then recompile: colcon build --symlink-install --packages-select dvl_a50

There are no .hpp files in your install/dvl_a50 directory, therefore it is impossible to link with the package library that is installed in the
Then we have to use the INSTALL ( DIRECTORY ...)  or INSTALL( FILE ...) that provides the list of files to be copied in the installation directory.

Without the added install command, the include directory files won't be installed in the process.

If you use the provided INSTALL command, then your header will be copied during installation, and other packages can link with the exported library.


I have found another problem with the driver, You define a node parameter in your config file: src/dvl_a50/config/dvl_a50.yml

led_enabled : true

But in the code you declare....

dvl_a50_ros2.cpp:        this->declare_parameter<bool>("enable_led", true);

Therefore, the defined parameter from the config file is unrecognized. It took a while to understang why the node was throwing an exception at configuration...

I have changed the declare_parameter to use "led_enable" insted of "enable_led"... I can create a pull request, or you can simply fix it. Maybe you prefer keeping your parameter definition, therefore a change in the config file is required.

Have a nice week-end!



[cid:c4b282a4-3ffa-4403-a5fb-c68ee39ef709]

Jean-Luc Bedwani, ing., M.Sc.A.
Chercheur
Robotique d'inspection et de maintenance
Institut de recherche d’Hydro-Québec
Tél. : 450-652-1354

hydroquebec.com<https://www.hydroquebec.com/>



[cid:fe5aeb09-d02b-4df7-b835-2ee068cb900b]





________________________________
De : Nikolas Dahn ***@***.***>
Envoyé : 18 octobre 2024 12:13
À : ndahn/dvl_a50 ***@***.***>
Cc : Bedwani, Jean-Luc ***@***.***>; Author ***@***.***>
Objet : Re: [ndahn/dvl_a50] Missing installation of the include directory. (PR #1)

Vous n’obtenez pas souvent d’e-mail à partir de ***@***.*** Pourquoi c’est important<https://aka.ms/LearnAboutSenderIdentification>

ATTENTION ! CE COURRIEL PROVIENT DE L’EXTERNE
Avant d’ouvrir ou de télécharger une pièce jointe ou de cliquer sur un lien, assurez-vous que le courriel provient d’une personne ou une organisation de confiance.
Faites preuve de vigilance, développez les bons réflexes, et ne téléchargez aucune pièce jointe non sollicitée ! Au besoin, cliquez sur le bouton Signaler le message sur votre barre d'outils.



Sorry, only saw your PR now. I'm not sure, but shouldn't this line already handle this?
https://github.com/ndahn/dvl_a50/blob/1e6a5304235facf53ecf82043fb5ba4c8569016b/CMakeLists.txt#L47C3-L47C31

**Comment by jbedwani** [comment]
I realise that my code does not require these .hpp files. Using the node as it is works well. Therefore there is no point going further with the pull request.

However, the fix for the parameter name declaration is required.




[cid:0cc8a67d-4d4b-4b60-a9d3-a3091214cf80]

Jean-Luc Bedwani, ing., M.Sc.A.
Chercheur
Robotique d'inspection et de maintenance
Institut de recherche d’Hydro-Québec
Tél. : 450-652-1354

hydroquebec.com<https://www.hydroquebec.com/>



[cid:d9a933ae-820f-4dc1-876e-b0908dbdb852]





________________________________
De : Bedwani, Jean-Luc ***@***.***>
Envoyé : 18 octobre 2024 18:24
À : ndahn/dvl_a50 ***@***.***>
Objet : Re: [ndahn/dvl_a50] Missing installation of the include directory. (PR #1)

Hi,

My understanding is that the INSTALL ( TARGETS ... ) defines the name of a target, then the following DESTINATION tags defines the diverse targeted directory name of the installation.

Using your CMakelist.txt

Clean the install directory for the package: rm -r ./install/dvl_a50
Then recompile: colcon build --symlink-install --packages-select dvl_a50

There are no .hpp files in your install/dvl_a50 directory, therefore it is impossible to link with the package library that is installed in the
Then we have to use the INSTALL ( DIRECTORY ...)  or INSTALL( FILE ...) that provides the list of files to be copied in the installation directory.

Without the added install command, the include directory files won't be installed in the process.

If you use the provided INSTALL command, then your header will be copied during installation, and other packages can link with the exported library.


I have found another problem with the driver, You define a node parameter in your config file: src/dvl_a50/config/dvl_a50.yml

led_enabled : true

But in the code you declare....

dvl_a50_ros2.cpp:        this->declare_parameter<bool>("enable_led", true);

Therefore, the defined parameter from the config file is unrecognized. It took a while to understang why the node was throwing an exception at configuration...

I have changed the declare_parameter to use "led_enable" insted of "enable_led"... I can create a pull request, or you can simply fix it. Maybe you prefer keeping your parameter definition, therefore a change in the config file is required.

Have a nice week-end!



[cid:c4b282a4-3ffa-4403-a5fb-c68ee39ef709]

Jean-Luc Bedwani, ing., M.Sc.A.
Chercheur
Robotique d'inspection et de maintenance
Institut de recherche d’Hydro-Québec
Tél. : 450-652-1354

hydroquebec.com<https://www.hydroquebec.com/>



[cid:fe5aeb09-d02b-4df7-b835-2ee068cb900b]





________________________________
De : Nikolas Dahn ***@***.***>
Envoyé : 18 octobre 2024 12:13
À : ndahn/dvl_a50 ***@***.***>
Cc : Bedwani, Jean-Luc ***@***.***>; Author ***@***.***>
Objet : Re: [ndahn/dvl_a50] Missing installation of the include directory. (PR #1)

Vous n’obtenez pas souvent d’e-mail à partir de ***@***.*** Pourquoi c’est important<https://aka.ms/LearnAboutSenderIdentification>

ATTENTION ! CE COURRIEL PROVIENT DE L’EXTERNE
Avant d’ouvrir ou de télécharger une pièce jointe ou de cliquer sur un lien, assurez-vous que le courriel provient d’une personne ou une organisation de confiance.
Faites preuve de vigilance, développez les bons réflexes, et ne téléchargez aucune pièce jointe non sollicitée ! Au besoin, cliquez sur le bouton Signaler le message sur votre barre d'outils.



Sorry, only saw your PR now. I'm not sure, but shouldn't this line already handle this?
https://github.com/ndahn/dvl_a50/blob/1e6a5304235facf53ecf82043fb5ba4c8569016b/CMakeLists.txt#L47C3-L47C31

**Comment by ndahn** [comment]
I see, you're right about that. Will fix it this afternoon!

**Comment by ndahn** [comment]
Includes are now also fixed, somehow they landed in *include/include/dvl_a50*.

**Pull request closed without merging**
